name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
    
    - name: Upload Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: my_artifact
          path: ./

  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my_artifact
          path: ./
      - name: View File
      - run: echo hello.txt